---
- name: Playbook
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: "Install mplayer"
      apt:
        name: mplayer
        state: present

    - name: "Install psutils"
      pip:
        name: psutil
        version: 5.4.3
        executable: pip3
